### ISSUE TITLE
experiment conditions

### ISSUE THREAD

**Issue by StaarFall** [genforce/freecontrol#17]
Thanks for the great work!
Was wondering if you could share the conditions (model hyperparams, benchmark setup, etc) used in the quantitative comparisons with other models and the condition images used to obtain the qualitative results for figures 1-12.

**Comment by SichengMo** [comment]
Thanks for reaching out. You can check our Implementation details paragraph in our experiments section. To reproduce our results in Table 1, you can fix λs = 600. 

We take the dataset from [Plug-and-Play ](https://github.com/MichalGeyer/plug-and-play) and use [ControlNet's processor ](https://github.com/genforce/freecontrol/blob/main/libs/utils/controlnet_processor.py) to convert them to different modalities.

**Comment by LexiPang** [comment]
We followed the instructions and used the default hyperparameters provided, but could not reproduce the results in your paper, what might be the reason for this?
1. Quantitative results
<img width="794" alt="c8a1beb7e582acd4327c261ac23c4ed" src="https://github.com/user-attachments/assets/fd277c58-e383-4463-90aa-6c55aa6bdbf4">
<img width="726" alt="7ad5f9f82a37a21997ebf07e85ff1eb" src="https://github.com/user-attachments/assets/83a61428-3f23-44d0-ae99-8001491edb6d">

For the implementation procedures that weren't mentioned in the paper, we completed it in the most reasonable way. We used the ImageNetR-TI2I dataset from the PnP paper, added inversion prompts to each of the condition images for DDIM inversion, and collected a semantic base for each of the 10 categories. We did not attempt to collect semantic bases for the additional related categories (such as the "bobcat", "tiger" in the photo below) because this would result in a large computational burden and we expected the semantic bases to be able to generalize.

![image](https://github.com/user-attachments/assets/d68a3030-4941-4d82-84aa-8fe9625fc3d2)
For self-similarity calculation we used the Splice DINO-ViT feature extractor with default hyperparameters (e.g. layer=11) and L2 distance between the self-similarity matrices.
For lpips, we used vgg.

2. Qualitative results
Below are some qualitative results using default hyperparameters provided in the paper, they still do not achieve comparable quality (paper results on the left, ours on the right):

<img width="391" alt="c73699859556e8cebf17e80e8858db3" src="https://github.com/user-attachments/assets/2e9bdf8d-89e5-4212-96d7-787b24542f29">

  Can you provide more details that might help solve the above issues? Thank you for your kind help!

**Comment by StaarFall** [comment]
We followed the instructions and used the default hyperparameters provided, but could not reproduce the results in your paper, what might be the reason for this?
1. Quantitative results
<img width="794" alt="c8a1beb7e582acd4327c261ac23c4ed" src="https://github.com/user-attachments/assets/fd277c58-e383-4463-90aa-6c55aa6bdbf4">
<img width="726" alt="7ad5f9f82a37a21997ebf07e85ff1eb" src="https://github.com/user-attachments/assets/83a61428-3f23-44d0-ae99-8001491edb6d">

For the implementation procedures that weren't mentioned in the paper, we completed it in the most reasonable way. We used the ImageNetR-TI2I dataset from the PnP paper, added inversion prompts to each of the condition images for DDIM inversion, and collected a semantic base for each of the 10 categories. We did not attempt to collect semantic bases for the additional related categories (such as the "bobcat", "tiger" in the photo below) because this would result in a large computational burden and we expected the semantic bases to be able to generalize.

![image](https://github.com/user-attachments/assets/d68a3030-4941-4d82-84aa-8fe9625fc3d2)
For self-similarity calculation we used the Splice DINO-ViT feature extractor with default hyperparameters (e.g. layer=11) and L2 distance between the self-similarity matrices.
For lpips, we used vgg.

2. Qualitative results
Below are some qualitative results using default hyperparameters provided in the paper, they still do not achieve comparable quality (paper results on the left, ours on the right):

<img width="391" alt="c73699859556e8cebf17e80e8858db3" src="https://github.com/user-attachments/assets/2e9bdf8d-89e5-4212-96d7-787b24542f29">

  Can you provide more details that might help solve the above issues? Thank you for your kind help!

**Comment by SichengMo** [comment]
Closed due to inactivity.
